---
- name: Cau hinh tren router
  hosts: all
  gather_facts: no

  tasks:
    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: output

    - debug: var=output.stdout
